language: python

python: 3.6

env: SETUPTOOLS_SCM_PRETEND_VERSION=0.0.1

services:
  - docker

addons:
  apt:
    packages:
    - libgdal-dev

# before_install:
#   - docker build -t openeo-grassgis-driver docker

install:
  - sed -i 's+pygdal==2.2.3.3+#pygdal==2.2.3.3+g' requirements.txt
  - pip install -r requirements.txt
  - python setup.py install

jobs:
  include:
    # - stage: test
    #   script: make test
    - stage: docs
      script: cd docs && make html && touch _build/html/.nojekyll

deploy:
  provider: pages
  target-branch: gh-pages
  local-dir: docs/_build/html
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
