# -*- coding: utf-8 -*-
"""This file includes all required openEO response schemas
"""
from typing import List, Optional, Dict
from .schema_base import JsonableObject, EoLinks
from .process_graph_schemas import ProcessGraph

__author__ = "Sören Gebbert"
__copyright__ = "Copyright 2018, Sören Gebbert, mundialis"
__maintainer__ = "Sören Gebbert"
__email__ = "soerengebbert@googlemail.com"


class OutputFormat(JsonableObject):
    """Information about the output format

    https://open-eo.github.io/openeo-api/v/0.3.0/apireference/#tag/Job-Management/paths/~1jobs~1{job_id}/get
    """

    def __init__(self, format: str, parameters: Dict[str, str]):

        self.format = format
        self.parameters = parameters


class JobError(JsonableObject):
    """This is the error response schema
    An error message that describes the problem during the batch job
    execution. May only be available if the `status` is `error`.
    The error MUST be cleared if the job is started again (i.e. the
    status changes to `queue`).

    code:
        required
        string (error_code)
        The code is either one of the standardized error codes or a
        custom error code.

    message:
        required
        string (error_message)
        A message explaining what the client may need to change or what
        difficulties the server is facing. By default the message must
        be sent in English language. Content Negotiation is used to localize
        the error messages: If an Accept-Language header is sent by the
        client and a translation is available, the message should be
        translated accordingly and the Content-Language header must be
        present in the response.
        example: "A sample error message.

    id:
        string (error_id)
        A back-end may add a unique identifier to the error response to be
        able to log and track errors with further non-disclosable details.
        A client could communicate this id to a back-end provider to get
        further information.
        example: "550e8400-e29b-11d4-a716-446655440000"

    links:
        array of links (error_links)
        Additional links related to this error, e.g. a resource that is
        explaining the error and potential solutions in-depth or a contact
        e-mail address.
    """

    def __init__(self, id: str = None, code: int, message: str,
                 links: List[Optional[EoLinks]] = list()):

        # Standardized status codes: https://open-eo.github.io/openeo-api/v/0.4.0/errors/index.html
        standardized_status_codes = {
            200: "OK",
            201: "Created",
            202: "Accepted",
            204: "No Content",
            400: "Bad Request",
            401: "Unauthorized",
            403: "Forbidden",
            404: "Not Found",
            500: "Internal Server Error",
            501: "Not Implemented"}
        self.id = id
        self.code = standardized_status_codes[code]
        self.message = message
        self.links = links


class JobInformation(JsonableObject):
    """Information about a job
    https://open-eo.github.io/openeo-api/v/0.4.0/apireference/#tag/Batch-Job-Management/paths/~1jobs/get{job_id}/get

    id:
        required
        string "^[A-Za-z0-9_\-\.~]+$" (job_id)
        Unique identifier of a job that is generated by the back-end during
        job submission. MUST match the specified pattern.

    title:
        string
        A short description to easily distinguish entities.

    description:
        string
        Detailed description to fully explain the entity.
        CommonMark 0.28 syntax MAY be used for rich text representation.

    status:
        required
        string
        The current status of a batch job.
        Default: "submitted"
        Enum:"submitted" "queued" "running" "canceled" "finished" "error"

    submitted:
        required (submitted)
        string <date-time>
        Date and time of creation, formatted as a RFC 3339 date-time.

    updated:
        string <date-time> (updated)
        Date and time of last status change, formatted as a RFC 3339 date-time.

    plan:
        string (billing_plan)
        The billing plan to process and charge the job with. The plans can
        be retrieved by calling GET /. Billing plans MUST be accepted
        case insensitive.

    costs:
        number (money)
        An amount of money or credits. The value MUST be specified in
        the currency the back-end is working with. The currency can be
        retrieved by calling GET /.

    budget:
        number (budget) Nullable
        Default: null
        Maximum amount of costs the user is allowed to produce. The value
        MUST be specified in the currency the back-end is working with.
        The currency can be retrieved by calling GET /. If possible, back-ends
        SHOULD reject jobs with openEO error PaymentRequired if the budget is
        too low to process the request completely. Otherwise, when reaching
        the budget jobs MAY try to return partial results if possible.
        Otherwise the request and results are discarded. Users SHOULD be
        warned by clients that reaching the budget MAY discard the results
        and that setting this value should be well-wrought. Setting the buget
        to null means there is no specified budget.
    """

    def __init__(self, job_id: str, title: str = None,
                 description: str = None, status: str = "submitted",
                 process_graph: ProcessGraph,
                 # output: Optional[OutputFormat],
                 submitted: str, updated: Optional[str] = None,
                 plan: str = None, cost: float=None, budget: float = None):
        # Test id
        pattern = "^[A-Za-z0-9_\-\.~]+$"
        x = re.search(pattern, job_id)
        if not x:
            es = ErrorSchema(id=str(datetime.now()), code=400,
                message="The id MUST match the following pattern: %s" % pattern)
            return make_response(es.to_json(), 400)
        self.job_id = job_id
        self.title = title
        self.description = description
        # Test Status
        if status in ["submitted", "queued", "running", "canceled", "finished", "error"]:
            es = ErrorSchema(id=str(datetime.now()), code=400,
                message="The status has to one of \"submitted\" \"queued\" \"running\" \"canceled\" \"finished\" \"error\"")
            return make_response(es.to_json(), 400)
        self.status = status
        self.submitted = submitted
        self.updated = updated
        self.plan = plan
        self.cost = cost
        self.budget = budget
        self.process_graph = process_graph
        # self.output = output


class JobList(JsonableObject):
    """A collection of job description entries

    https://open-eo.github.io/openeo-api/v/0.3.0/apireference/#tag/Job-Management/paths/~1jobs/get
    """

    def __init__(self, jobs: List[JobInformation],
                 links: Optional[EoLinks] = None):
        self.jobs = jobs
        self.links = links
