# type=ref,event=branch # on push, tag = main
# type=ref,event=tag # on push tag, tag = 1.2.3
# type=sha # tag = sha-ad132f5
# # type=semver,pattern={{raw}} # tag = <tag>
# # type=semver,pattern={{version}} # tag = 1.2.3
# # type=semver,pattern={{major}}.{{minor}} # tag = 1.2
# # type=semver,pattern={{major}} # tag = 1
# latest=auto # takes care of tag latest

name: Docker build

on:
  push:
    branches: [ master, gha-docker ]
    tags: [ '*.*.*' ]
    paths-ignore: ['docs/**']
  release:
    types: [published, created]

jobs:
  docker:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker metadata
        # https://github.com/marketplace/actions/docker-metadata-action
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: mmacata/openeo-grassgis-driver
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
          flavor: |
            latest=auto
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      -
        name: Build and push
        # https://github.com/marketplace/actions/build-and-push-docker-images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          file: docker/Dockerfile
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
