# https://github.com/marketplace/actions/build-and-push-docker-images
# https://github.com/marketplace/actions/docker-metadata-action
# type=ref,event=tag # on push tag, tag = 1.2.3
# type=sha # tag = sha-ad132f5
# latest=auto # takes care of tag latest

name: Docker build and push

on:
  push:
    branches: [master]
    tags: ['*.*.*']
    paths-ignore: ['docs/**']
  release:
    types: [published]

jobs:
  docker:
    name: docker build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create image and tag names
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mundialis/openeo-grassgis-driver
          tags: |
            type=ref,event=tag
            type=sha
          flavor: |
            latest=auto
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          file: docker/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
