name: Docker build

on:
  push:
    paths-ignore: ['docs/**']
    branches: [ master, gha-docker ]

jobs:
  docker:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: mmacata/openeo-grassgis-driver:latest
          file: docker/Dockerfile
          no-cache: false
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
